# Generated by Django 2.1.8 on 2019-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchID', models.IntegerField()),
                ('OfficeName', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
            ],
        ),
    ]
